---
title: "Homework 3"
output: html_document
date: '2025-01-29'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



Question 1: 
```
FIND: \s{2,} 
REPLACE: ,
```
This expression finds anywhere where its more than two spaces and replaces with a comma.


Question 2: 
```
FIND: (\b\w+),\s*(\b\w+),\s*(.*) 
REPLACE: \2 \1 (\3)
```
This expression captures the first word, second word, and any characters after second comma. It replaces it with the second word first (without commas), first word second, then places all characters from third capture in parentheses. 

Question 3: 
```
FIND: (\b\.mp3 \b) 
REPLACE: \1\n 
```
This expression captures .mp3 at every instance and replaces it with a line break.

Question 4: 
```
FIND: (\d+)\s+(.*)(\.mp3) 
REPLACE: \2_\1\3
```
This expression captures the first digits, the spaces, and anything that comes after, except for the .mp3 which is captured afterwards. It replaces is so that the 2nd capture comes first, 1st capture comes second (after an underscore), and the .mp3 comes last.

Question 5: 
```
FIND: (\w)\w+,(\w+,)\d+.+,(\d+) 
REPLACE: \1_\2\3
```
This expression capture the first letter, word after first comma, and last number, then removes the characters that are not captured.

Question 6: 
```
FIND: (\w)\w+,(\w{4})\w+.+,(\d+) 
REPLACE: \1_\2\,\3
```
This expression captures the first letter, first four characters of the text after the first comma, and the last digits after the last comma. It replaces by removing all non-captured text and adding an underscore between the 1st and 2nd captured text.

Question 7: 
```
FIND: (\w{3})\w+,(\w{3})\w+,(\d+.+),(\d+) 
REPLACE: \1\2, \4, \3
```
This expression captures the first three letters of first word, first 3 letters of second word, first number after comma, and second number after comma then replaces by removing all non-captured text and rearranging so 1 and 2 are fused and the second number comes first with commas in between numbers.

Question 8: 
```
FIND: [^a-zA-Z0-9,/.\s] 
REPLACE:    
```
This expression finds all special characters besides / . , and replaces them with nothing.
    
```
FIND: (^(?:[^,]*,){8}(?:[^,]*))(\s)(.*) 
REPLACE: \1\3 
```
This expression captures everything up to 8 commas in a line and the column of interest. It captures the extra space, then everything else in the line and replaces just the 1st capture and 3rd capture to remove the spaces.

