---
title: "Homework5"
output: html_document
date: '2025-02-12'
---

Question 1:

```{r}
n_dims <- runif(1, 3, 10)

vec <- c(1:(n_dims^2))

samp <- sample(vec)

m <- matrix(samp, nrow = n_dims, ncol = n_dims)
print(m)

trans_m <- t(m)
print(trans_m)

sum(trans_m[1,])
mean(trans_m[1,])

sum(trans_m[n_dims,])
mean(trans_m[n_dims,])

eigen <- eigen(trans_m)

typeof(eigen)

```


Question 2:

```{r}

r_num <- runif(16)
my_matrix <- matrix(r_num, 4, 4)

r_num2 <- runif(100)
my_logical <- r_num2<50

my_letters <- sample(letters, length(letters))
print(my_letters)

my_list <- list(my_matrix,my_logical, my_letters)

my_list2 <- list(my_matrix[2,2], my_logical[2], my_letters[2])

sapply(my_list2, typeof)

vec2 <- c(my_matrix[2,2], my_logical[2], my_letters[2])
typeof(vec2)

```

Question 3:

```{r}

my_unis <- runif(26, 0, 10)
my_letters <- sample(LETTERS, length(LETTERS))

df <- data.frame(my_unis,my_letters)

#for the first variable, use a single line of code in R to select 4 random rows and replace the numerical values in those rows with NA.
df[sample(nrow(df), 4), "my_unis"] <- NA

#for the first variable, write a single line of R code to identify which rows have the missing values.
which(!complete.cases(df$my_unis))

#re-order the entire data frame to arrange the second variable in alphabetical order          
df <- df[order(df$my_letters), ]

#calculate the column mean for the first variable
mean(df$my_unis, na.rm = T)


```











